/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IFtsoRegistry, IFtsoRegistryInterface } from "../IFtsoRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
    ],
    name: "getCurrentPriceWithDecimals",
    outputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_assetPriceUsdDecimals",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
    ],
    name: "getFtsoBySymbol",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSupportedSymbols",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFtsoRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoRegistryInterface {
    return new Interface(_abi) as IFtsoRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFtsoRegistry {
    return new Contract(address, _abi, runner) as unknown as IFtsoRegistry;
  }
}
