/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFtsoRegistry__factory } from "./IFtsoRegistry__factory";
export { ScamGuardian__factory } from "./ScamGuardian__factory";
