/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IFtsoRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCurrentPriceWithDecimals"
      | "getFtsoBySymbol"
      | "getSupportedSymbols"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCurrentPriceWithDecimals",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFtsoBySymbol",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedSymbols",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getCurrentPriceWithDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFtsoBySymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedSymbols",
    data: BytesLike
  ): Result;
}

export interface IFtsoRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IFtsoRegistry;
  waitForDeployment(): Promise<this>;

  interface: IFtsoRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCurrentPriceWithDecimals: TypedContractMethod<
    [_symbol: string],
    [
      [bigint, bigint, bigint] & {
        _price: bigint;
        _timestamp: bigint;
        _assetPriceUsdDecimals: bigint;
      }
    ],
    "view"
  >;

  getFtsoBySymbol: TypedContractMethod<[_symbol: string], [string], "view">;

  getSupportedSymbols: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCurrentPriceWithDecimals"
  ): TypedContractMethod<
    [_symbol: string],
    [
      [bigint, bigint, bigint] & {
        _price: bigint;
        _timestamp: bigint;
        _assetPriceUsdDecimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFtsoBySymbol"
  ): TypedContractMethod<[_symbol: string], [string], "view">;
  getFunction(
    nameOrSignature: "getSupportedSymbols"
  ): TypedContractMethod<[], [string[]], "view">;

  filters: {};
}
