/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFtsoRegistry } from "./IFtsoRegistry";
export type { ScamGuardian } from "./ScamGuardian";
export * as factories from "./factories";
export { IFtsoRegistry__factory } from "./factories/IFtsoRegistry__factory";
export { ScamGuardian__factory } from "./factories/ScamGuardian__factory";
