/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ScamGuardianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedAgent"
      | "ftsoRegistry"
      | "getVerifiedPrice"
      | "nextRequestId"
      | "requestAnalysis"
      | "requests"
      | "results"
      | "setAuthorizedAgent"
      | "submitResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AnalysisCompleted" | "AnalysisRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ftsoRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAnalysis",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "results",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ftsoRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAnalysis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
}

export namespace AnalysisCompletedEvent {
  export type InputTuple = [requestId: BigNumberish, reportJson: string];
  export type OutputTuple = [requestId: bigint, reportJson: string];
  export interface OutputObject {
    requestId: bigint;
    reportJson: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AnalysisRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    encryptedData: string
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    encryptedData: string
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    encryptedData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ScamGuardian extends BaseContract {
  connect(runner?: ContractRunner | null): ScamGuardian;
  waitForDeployment(): Promise<this>;

  interface: ScamGuardianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedAgent: TypedContractMethod<[], [string], "view">;

  ftsoRegistry: TypedContractMethod<[], [string], "view">;

  getVerifiedPrice: TypedContractMethod<
    [_symbol: string],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;

  nextRequestId: TypedContractMethod<[], [bigint], "view">;

  requestAnalysis: TypedContractMethod<
    [_encryptedData: string],
    [bigint],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        requester: string;
        encryptedData: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  results: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { reportJson: string; isProcessed: boolean }],
    "view"
  >;

  setAuthorizedAgent: TypedContractMethod<
    [_newAgent: AddressLike],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [_requestId: BigNumberish, _reportJson: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedAgent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ftsoRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getVerifiedPrice"
  ): TypedContractMethod<
    [_symbol: string],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestAnalysis"
  ): TypedContractMethod<[_encryptedData: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        requester: string;
        encryptedData: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { reportJson: string; isProcessed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedAgent"
  ): TypedContractMethod<[_newAgent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _reportJson: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AnalysisCompleted"
  ): TypedContractEvent<
    AnalysisCompletedEvent.InputTuple,
    AnalysisCompletedEvent.OutputTuple,
    AnalysisCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AnalysisRequested"
  ): TypedContractEvent<
    AnalysisRequestedEvent.InputTuple,
    AnalysisRequestedEvent.OutputTuple,
    AnalysisRequestedEvent.OutputObject
  >;

  filters: {
    "AnalysisCompleted(uint256,string)": TypedContractEvent<
      AnalysisCompletedEvent.InputTuple,
      AnalysisCompletedEvent.OutputTuple,
      AnalysisCompletedEvent.OutputObject
    >;
    AnalysisCompleted: TypedContractEvent<
      AnalysisCompletedEvent.InputTuple,
      AnalysisCompletedEvent.OutputTuple,
      AnalysisCompletedEvent.OutputObject
    >;

    "AnalysisRequested(uint256,address,string)": TypedContractEvent<
      AnalysisRequestedEvent.InputTuple,
      AnalysisRequestedEvent.OutputTuple,
      AnalysisRequestedEvent.OutputObject
    >;
    AnalysisRequested: TypedContractEvent<
      AnalysisRequestedEvent.InputTuple,
      AnalysisRequestedEvent.OutputTuple,
      AnalysisRequestedEvent.OutputObject
    >;
  };
}
